# Generated by Django 6.0 on 2026-03-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='attendee_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='reminder_minutes_before',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='reminders_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
