# Generated by Django 6.0 on 2026-03-04 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userpresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='parent_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tasks', to='core.note'),
        ),
    ]
