# Generated by Django 6.0 on 2026-03-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customer_customerquote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerquote',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('sent', 'Gönderildi'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('revision', 'Revizyon Bekliyor')], default='draft', max_length=20),
        ),
    ]
