# Generated by Django 6.0 on 2026-03-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_customerquote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='annual_revenue_expectation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='competitor_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Bireysel'), ('company', 'Kurumsal'), ('public', 'Kamu'), ('partner', 'Is Ortagi')], default='company', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='decision_maker',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='customer',
            name='decision_maker_contact',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='e_invoice_alias',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_e_invoice_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_contacted_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='next_follow_up_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pain_points',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_contact_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='priority',
            field=models.CharField(choices=[('low', 'Dusuk'), ('medium', 'Orta'), ('high', 'Yuksek'), ('critical', 'Kritik')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customerquote',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customerquote',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customerquote',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customerquote',
            name='probability_percent',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='customerquote',
            name='scope_items',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerquote',
            name='stage',
            field=models.CharField(choices=[('qualification', 'On Gorusme'), ('proposal', 'Teklif Hazirlaniyor'), ('negotiation', 'Muzakere'), ('final', 'Final Asamasi')], default='proposal', max_length=20),
        ),
        migrations.AddField(
            model_name='customerquote',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AddField(
            model_name='customerquote',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
