from django.urls import path

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from .views import (
    AnnouncementListCreateAPIView,
    CalendarEventDetailAPIView,
    CalendarEventListCreateAPIView,
    CommentReactionToggleAPIView,
    ConversationListCreateAPIView,
    ConversationMessageListCreateAPIView,
    CustomerDetailAPIView,
    CustomerListCreateAPIView,
    EmailVerificationConfirmAPIView,
    EmailVerificationRequestAPIView,
    FinanceAlertDetailAPIView,
    FinanceAlertListCreateAPIView,
    GlobalSearchAPIView,
    LoginAPIView,
    NoteDetailAPIView,
    NoteListCreateAPIView,
    NotificationListAPIView,
    NotificationMarkAllReadAPIView,
    OrganizationInviteAPIView,
    OrganizationListCreateAPIView,
    PasswordResetConfirmAPIView,
    PasswordResetRequestAPIView,
    ProjectDetailAPIView,
    ProjectListCreateAPIView,
    RegisterAPIView,
    TaskAttachmentUploadAPIView,
    TaskCommentCreateAPIView,
    TaskDetailAPIView,
    TaskListCreateAPIView,
    TaskSubTaskListCreateAPIView,
    TaskSubTaskReorderAPIView,
    TagListCreateAPIView,
    SubTaskDetailAPIView,
    UserDetailAPIView,
)


urlpatterns = [
    path('schema', SpectacularAPIView.as_view(), name='api_schema'),
    path('docs', SpectacularSwaggerView.as_view(url_name='api_schema'), name='api_docs'),
    path('auth/register', RegisterAPIView.as_view(), name='api_register'),
    path('auth/login', LoginAPIView.as_view(), name='api_login'),
    path('auth/password-reset/request', PasswordResetRequestAPIView.as_view(), name='api_password_reset_request'),
    path('auth/password-reset/confirm', PasswordResetConfirmAPIView.as_view(), name='api_password_reset_confirm'),
    path('auth/email-verification/request', EmailVerificationRequestAPIView.as_view(), name='api_email_verification_request'),
    path('auth/email-verification/confirm', EmailVerificationConfirmAPIView.as_view(), name='api_email_verification_confirm'),
    path('organizations', OrganizationListCreateAPIView.as_view(), name='api_organizations'),
    path('organizations/<uuid:pk>/invite', OrganizationInviteAPIView.as_view(), name='api_organization_invite'),
    path('projects', ProjectListCreateAPIView.as_view(), name='api_projects'),
    path('projects/<int:pk>', ProjectDetailAPIView.as_view(), name='api_project_detail'),
    path('tags', TagListCreateAPIView.as_view(), name='api_tags'),
    path('tasks', TaskListCreateAPIView.as_view(), name='api_tasks'),
    path('tasks/<int:pk>', TaskDetailAPIView.as_view(), name='api_task_detail'),
    path('tasks/<int:pk>/subtasks', TaskSubTaskListCreateAPIView.as_view(), name='api_task_subtasks'),
    path('tasks/<int:pk>/subtasks/reorder', TaskSubTaskReorderAPIView.as_view(), name='api_task_subtasks_reorder'),
    path('tasks/<int:pk>/comments', TaskCommentCreateAPIView.as_view(), name='api_task_comments'),
    path('tasks/<int:pk>/attachments', TaskAttachmentUploadAPIView.as_view(), name='api_task_attachments'),
    path('subtasks/<int:pk>', SubTaskDetailAPIView.as_view(), name='api_subtask_detail'),
    path('comments/<int:pk>/reactions/toggle', CommentReactionToggleAPIView.as_view(), name='api_comment_reactions_toggle'),
    path('notifications', NotificationListAPIView.as_view(), name='api_notifications'),
    path('notifications/mark-all-read', NotificationMarkAllReadAPIView.as_view(), name='api_notifications_mark_all_read'),
    path('notes', NoteListCreateAPIView.as_view(), name='api_notes'),
    path('notes/<int:pk>', NoteDetailAPIView.as_view(), name='api_note_detail'),
    path('users/<int:pk>', UserDetailAPIView.as_view(), name='api_user_detail'),
    path('announcements', AnnouncementListCreateAPIView.as_view(), name='api_announcements'),
    path('calendar-events', CalendarEventListCreateAPIView.as_view(), name='api_calendar_events'),
    path('calendar-events/<int:pk>', CalendarEventDetailAPIView.as_view(), name='api_calendar_event_detail'),
    path('customers', CustomerListCreateAPIView.as_view(), name='api_customers'),
    path('customers/<int:pk>', CustomerDetailAPIView.as_view(), name='api_customer_detail'),
    path('finance-alerts', FinanceAlertListCreateAPIView.as_view(), name='api_finance_alerts'),
    path('finance-alerts/<int:pk>', FinanceAlertDetailAPIView.as_view(), name='api_finance_alert_detail'),
    path('conversations', ConversationListCreateAPIView.as_view(), name='api_conversations'),
    path('conversations/<int:pk>/messages', ConversationMessageListCreateAPIView.as_view(), name='api_conversation_messages'),
    path('search', GlobalSearchAPIView.as_view(), name='api_search'),
]
